//! Differential-test fixture generator for moonbit-bimap.
//!
//! Runs the reference implementation — the Rust `bimap` crate v0.6.3, the
//! porting source documented in `docs/SPEC.md` §0 — over the two operation
//! streams shared with the MoonBit tests:
//!
//!   1. the hand-crafted golden C0–C4 sequence (shared with `bimap_test.mbt`
//!      and `model_test.mbt`), and
//!   2. the 6000-step deterministic LCG stream (same seed, moduli, and op
//!      mapping as `model_test.mbt`).
//!
//! It emits `src/differential_fixture_test.mbt`: for every step, the observed
//! `Overwritten` classification (or `Option`/`Result` observation) plus the
//! resulting length, and finally the pair set. The MoonBit side
//! (`src/differential_test.mbt`) replays the same streams through the real
//! `BiMap` and must reproduce every observation exactly.
//!
//! Usage:
//!   cargo run --release -- ../../src/differential_fixture_test.mbt

use bimap::{BiMap, Overwritten};
use std::env;
use std::fmt::Write as _;
use std::fs;

const STEPS: u64 = 6000;

/// Same LCG as `src/model_test.mbt`: seed 0x1234_5678, mask to 31 bits.
fn next_state(state: u64) -> u64 {
    (state.wrapping_mul(1_103_515_245).wrapping_add(12_345)) & 0x7FFF_FFFF
}

/// Encode an `insert` result into the fixture's string format.
fn classify(o: Overwritten<i32, i32>) -> String {
    match o {
        Overwritten::Neither => "Neither".to_string(),
        Overwritten::Left(l, r) => format!("Left({},{})", l, r),
        Overwritten::Right(l, r) => format!("Right({},{})", l, r),
        Overwritten::Both((l1, r1), (l2, r2)) => {
            format!("Both(({},{}),({},{}))", l1, r1, l2, r2)
        }
        Overwritten::Pair(l, r) => format!("Pair({},{})", l, r),
    }
}

fn main() {
    let out_path = env::args()
        .nth(1)
        .expect("usage: diffgen <path to differential_fixture_test.mbt>");

    let mut out = String::new();
    writeln!(
        out,
        "// GENERATED by `tools/diffgen` (reference: Rust `bimap` crate v0.6.3, the porting source)."
    )
    .unwrap();
    writeln!(
        out,
        "// Regenerate: cd tools/diffgen && cargo run --release -- ../../src/differential_fixture_test.mbt"
    )
    .unwrap();
    writeln!(
        out,
        "// then run `moon fmt`. Do not edit by hand; see tools/diffgen/README.md."
    )
    .unwrap();
    writeln!(out).unwrap();

    // 1. Golden C0-C4 sequence (shared with bimap_test.mbt / model_test.mbt).
    let golden: [(i32, i32); 6] = [(1, 10), (2, 20), (1, 40), (3, 20), (1, 20), (1, 20)];
    let mut map: BiMap<i32, i32> = BiMap::new();
    writeln!(out, "let diff_golden_observations : Array[String] = [").unwrap();
    for (l, r) in golden {
        let o = map.insert(l, r);
        writeln!(out, "  \"{}|{}\",", classify(o), map.len()).unwrap();
    }
    writeln!(out, "]").unwrap();
    writeln!(out).unwrap();

    // 2. 6000-step LCG stream (same derivation as model_test.mbt:
    //    op = state % 4; l = (state >> 6) % 15; r = (state >> 14) % 15;
    //    op 0 = insert, 1 = remove_by_left, 2 = remove_by_right,
    //    3 = insert_no_overwrite).
    let mut map: BiMap<i32, i32> = BiMap::new();
    let mut state: u64 = 0x1234_5678;
    writeln!(out, "let diff_observations : Array[String] = [").unwrap();
    for _ in 0..STEPS {
        state = next_state(state);
        let op = state % 4;
        let l = ((state >> 6) % 15) as i32;
        let r = ((state >> 14) % 15) as i32;
        let obs = match op {
            0 => classify(map.insert(l, r)),
            // Rust bimap's remove_by_left/right returns the whole removed
            // (L, R) pair; the observable counterpart of MoonBit's
            // `remove_by_left(l) -> R?` is the pair's RIGHT value.
            1 => match map.remove_by_left(&l) {
                Some((l0, r0)) => {
                    assert_eq!(l0, l, "remove_by_left returned a mismatched left key");
                    format!("Some({})", r0)
                }
                None => "None".to_string(),
            },
            // ...and of `remove_by_right(r) -> L?` the pair's LEFT key.
            2 => match map.remove_by_right(&r) {
                Some((l0, r0)) => {
                    assert_eq!(r0, r, "remove_by_right returned a mismatched right value");
                    format!("Some({})", l0)
                }
                None => "None".to_string(),
            },
            _ => match map.insert_no_overwrite(l, r) {
                Ok(()) => "Ok".to_string(),
                Err(_) => "Err".to_string(),
            },
        };
        writeln!(out, "  \"{}|{}\",", obs, map.len()).unwrap();
    }
    writeln!(out, "]").unwrap();
    writeln!(out).unwrap();

    // Final pair set, sorted by left key (left keys are unique in a bijection).
    let mut pairs: Vec<(i32, i32)> = map.iter().map(|(l, r)| (*l, *r)).collect();
    pairs.sort();
    writeln!(out, "let diff_final_pairs : Array[(Int, Int)] = [").unwrap();
    for (l, r) in pairs {
        writeln!(out, "  ({}, {}),", l, r).unwrap();
    }
    writeln!(out, "]").unwrap();

    fs::write(&out_path, out).expect("failed to write fixture");
    println!("wrote {}", out_path);
}
